// GPU Particle System Shaders — volumetric smoke trails for missiles and planes.
// Compute shader simulates particles; VS/PS render as soft camera-facing billboards.
// Sources are in VulkanHLSL/GPUParticleUpdate.hlsl and GPUParticleRender.hlsl;
// the .inc siblings are generated by scripts/generate_inc.py.

#pragma once

namespace Render {

static const char* g_shaderGPUParticleUpdate =
#include "VulkanHLSL/GPUParticleUpdate.hlsl.inc"
;

static const char* g_shaderGPUParticleRender =
#include "VulkanHLSL/GPUParticleRender.hlsl.inc"
;

} // namespace Render
