#pragma once

// HLSL shader source strings for the D3D11 runtime-compile path.
//
// The authoritative source for every shader below lives in a `.hlsl` file
// under VulkanHLSL/ — that file is what dxc consumes for the Vulkan SPIR-V
// build, and it's the one a developer edits. The `.hlsl.inc` siblings are
// auto-generated by `scripts/generate_inc.py` (invoked as a PreBuildEvent
// in the vcxproj and as a custom_command in CMake); they wrap the .hlsl
// contents in `R"HLSL(...)HLSL"` raw-string literals so this header can
// splice them into `static const char*` initializers for D3DCompile at
// runtime. Both paths consume the same bytes.
//
// DO NOT edit any `.hlsl.inc` file by hand — edits are overwritten on
// every build. Edit the `.hlsl` file.

namespace Render
{

static const char* g_shader3D =
#include "VulkanHLSL/Shader3D.hlsl.inc"
;

static const char* g_shaderSnow =
#include "VulkanHLSL/ShaderSnow.hlsl.inc"
;

static const char* g_shaderDecal =
#include "VulkanHLSL/ShaderDecal.hlsl.inc"
;

static const char* g_shaderPost =
#include "VulkanHLSL/ShaderPost.hlsl.inc"
;

static const char* g_shaderFSR =
#include "VulkanHLSL/ShaderFSR.hlsl.inc"
;

static const char* g_shaderParticleFX =
#include "VulkanHLSL/ShaderParticleFX.hlsl.inc"
;

static const char* g_shaderShockwave =
#include "VulkanHLSL/ShaderShockwave.hlsl.inc"
;

static const char* g_shaderGodRays =
#include "VulkanHLSL/ShaderGodRays.hlsl.inc"
;

static const char* g_shaderCinematic =
#include "VulkanHLSL/ShaderCinematic.hlsl.inc"
;

static const char* g_shaderVolumetric =
#include "VulkanHLSL/ShaderVolumetric.hlsl.inc"
;

static const char* g_shaderLensFlare =
#include "VulkanHLSL/ShaderLensFlare.hlsl.inc"
;

static const char* g_shaderFilmGrain =
#include "VulkanHLSL/ShaderFilmGrain.hlsl.inc"
;

static const char* g_shaderSharpen =
#include "VulkanHLSL/ShaderSharpen.hlsl.inc"
;

static const char* g_shaderTiltShift =
#include "VulkanHLSL/ShaderTiltShift.hlsl.inc"
;

static const char* g_shader2D =
#include "VulkanHLSL/Shader2D.hlsl.inc"
;

static const char* g_shaderDebug =
#include "VulkanHLSL/ShaderDebug.hlsl.inc"
;

static const char* g_shaderShadowVolumeExtrude =
#include "VulkanHLSL/ShaderShadowVolumeExtrude.hlsl.inc"
;

static const char* g_shaderShadowVolumeDarken =
#include "VulkanHLSL/ShaderShadowVolumeDarken.hlsl.inc"
;

static const char* g_shaderShadowProjectedDecal =
#include "VulkanHLSL/ShaderShadowProjectedDecal.hlsl.inc"
;

} // namespace Render
