#pragma once
// Stub — WOL browser COM interfaces not used in D3D11 remaster.
// Original was generated by MIDL from BrowserDispatch.idl.
#include <unknwn.h>

// {53D62F24-21A5-11D5-9F03-444553540000}
DEFINE_GUID(IID_IBrowserDispatch,
    0x53D62F24, 0x21A5, 0x11D5, 0x9F, 0x03, 0x44, 0x45, 0x53, 0x54, 0x00, 0x00);

MIDL_INTERFACE("53D62F24-21A5-11D5-9F03-444553540000")
IBrowserDispatch : public IDispatch
{
public:
    virtual HRESULT STDMETHODCALLTYPE cycleAlternateText() = 0;
    virtual HRESULT STDMETHODCALLTYPE cycleBackgroundColor() = 0;
    virtual HRESULT STDMETHODCALLTYPE cycleActiveBackgroundColor() = 0;
    virtual HRESULT STDMETHODCALLTYPE cycleActiveTextColor() = 0;
    virtual HRESULT STDMETHODCALLTYPE cycleTextColor() = 0;
    virtual HRESULT STDMETHODCALLTYPE cycleBackgroundAlpha() = 0;
    virtual HRESULT STDMETHODCALLTYPE cycleURL() = 0;
    virtual HRESULT STDMETHODCALLTYPE cycleFont() = 0;
    virtual HRESULT STDMETHODCALLTYPE cycleHighliteColor() = 0;
    virtual HRESULT STDMETHODCALLTYPE cycleAlternateHighliteColor() = 0;
    virtual HRESULT STDMETHODCALLTYPE cycleHighliteTextColor() = 0;
    virtual HRESULT STDMETHODCALLTYPE cycleAlternateHighliteTextColor() = 0;
    virtual HRESULT STDMETHODCALLTYPE cycleHighliteAlpha() = 0;
    virtual HRESULT STDMETHODCALLTYPE cycleDisabledTextColor() = 0;
    virtual HRESULT STDMETHODCALLTYPE cycleHiliteFont() = 0;
    virtual HRESULT STDMETHODCALLTYPE cycleDisabledFont() = 0;
    virtual HRESULT STDMETHODCALLTYPE cycleToolTipColor() = 0;
    virtual HRESULT STDMETHODCALLTYPE cycleToolTipAlpha() = 0;
    virtual HRESULT STDMETHODCALLTYPE cycleToolTipTextColor() = 0;
    virtual HRESULT STDMETHODCALLTYPE cycleToolTipFont() = 0;
    virtual HRESULT STDMETHODCALLTYPE cycleToolTipDelay() = 0;
    virtual HRESULT STDMETHODCALLTYPE cycleEditColor() = 0;
    virtual HRESULT STDMETHODCALLTYPE cycleEditAlpha() = 0;
    virtual HRESULT STDMETHODCALLTYPE cycleEditTextColor() = 0;
    virtual HRESULT STDMETHODCALLTYPE cycleEditFont() = 0;
    virtual HRESULT STDMETHODCALLTYPE cycleSliderColor() = 0;
    virtual HRESULT STDMETHODCALLTYPE cycleSliderAlpha() = 0;
    virtual HRESULT STDMETHODCALLTYPE cycleScrollbarColor() = 0;
    virtual HRESULT STDMETHODCALLTYPE cycleScrollbarAlpha() = 0;
    virtual HRESULT STDMETHODCALLTYPE cycleSliderThumbColor() = 0;
    virtual HRESULT STDMETHODCALLTYPE cycleSliderThumbAlpha() = 0;
    virtual HRESULT STDMETHODCALLTYPE cycleListboxColor() = 0;
    virtual HRESULT STDMETHODCALLTYPE cycleListboxAlpha() = 0;
    virtual HRESULT STDMETHODCALLTYPE cycleComboboxColor() = 0;
    virtual HRESULT STDMETHODCALLTYPE cycleComboboxAlpha() = 0;
    virtual HRESULT STDMETHODCALLTYPE cycleCheckboxColor() = 0;
    virtual HRESULT STDMETHODCALLTYPE cycleCheckboxAlpha() = 0;
    virtual HRESULT STDMETHODCALLTYPE cycleRadioButtonColor() = 0;
    virtual HRESULT STDMETHODCALLTYPE cycleRadioButtonAlpha() = 0;
    virtual HRESULT STDMETHODCALLTYPE cycleProgressBarColor() = 0;
    virtual HRESULT STDMETHODCALLTYPE cycleProgressBarAlpha() = 0;
    virtual HRESULT STDMETHODCALLTYPE cycleProgressBarIndicatorColor() = 0;
    virtual HRESULT STDMETHODCALLTYPE cycleProgressBarIndicatorAlpha() = 0;
    virtual HRESULT STDMETHODCALLTYPE cycleStaticTextColor() = 0;
    virtual HRESULT STDMETHODCALLTYPE cycleStaticTextAlpha() = 0;
    virtual HRESULT STDMETHODCALLTYPE cycleStaticTextFont() = 0;
    virtual HRESULT STDMETHODCALLTYPE cycleWindowColor() = 0;
    virtual HRESULT STDMETHODCALLTYPE cycleWindowAlpha() = 0;
    virtual HRESULT STDMETHODCALLTYPE cycleWindowBorder() = 0;
    virtual HRESULT STDMETHODCALLTYPE cycleTextAlignment() = 0;
    virtual HRESULT STDMETHODCALLTYPE cycleTextVerticalAlignment() = 0;
    virtual HRESULT STDMETHODCALLTYPE cycleImageAlignment() = 0;
    virtual HRESULT STDMETHODCALLTYPE cycleImageVerticalAlignment() = 0;
    virtual HRESULT STDMETHODCALLTYPE cycleImage() = 0;
    virtual HRESULT STDMETHODCALLTYPE cycleActiveImage() = 0;
    virtual HRESULT STDMETHODCALLTYPE cycleHiliteImage() = 0;
    virtual HRESULT STDMETHODCALLTYPE cycleWindowImage() = 0;
    virtual HRESULT STDMETHODCALLTYPE cycleActiveWindowImage() = 0;
    virtual HRESULT STDMETHODCALLTYPE cycleHiliteWindowImage() = 0;
    virtual HRESULT STDMETHODCALLTYPE cycleImageRepeat() = 0;
    virtual HRESULT STDMETHODCALLTYPE cycleWindowImageRepeat() = 0;
    virtual HRESULT STDMETHODCALLTYPE cycleAltGUIBehavior() = 0;
    virtual HRESULT STDMETHODCALLTYPE cycleGUIBehavior() = 0;
    virtual HRESULT STDMETHODCALLTYPE cycleControlBar() = 0;
    virtual HRESULT STDMETHODCALLTYPE cycleHotKey() = 0;
    virtual HRESULT STDMETHODCALLTYPE cycleLeftAnchor() = 0;
    virtual HRESULT STDMETHODCALLTYPE cycleRightAnchor() = 0;
    virtual HRESULT STDMETHODCALLTYPE cycleTopAnchor() = 0;
    virtual HRESULT STDMETHODCALLTYPE cycleBottomAnchor() = 0;
    virtual HRESULT STDMETHODCALLTYPE cyclePosition() = 0;
    virtual HRESULT STDMETHODCALLTYPE cycleSize() = 0;
    virtual HRESULT STDMETHODCALLTYPE cycleGadgetName() = 0;
    virtual HRESULT STDMETHODCALLTYPE cycleWindowName() = 0;
    virtual HRESULT STDMETHODCALLTYPE cycleGameWindowName() = 0;
    virtual HRESULT STDMETHODCALLTYPE cycleFullscreenToggle() = 0;
    virtual HRESULT STDMETHODCALLTYPE cycleNavigationText() = 0;
    virtual HRESULT STDMETHODCALLTYPE cycleNavigationURL() = 0;
    virtual HRESULT STDMETHODCALLTYPE cycleMainMenu() = 0;
    virtual HRESULT STDMETHODCALLTYPE cycleBack() = 0;
    virtual HRESULT STDMETHODCALLTYPE cycleForward() = 0;
    virtual HRESULT STDMETHODCALLTYPE cycleRefresh() = 0;
    virtual HRESULT STDMETHODCALLTYPE cycleStop() = 0;
    virtual HRESULT STDMETHODCALLTYPE cycleNavigate(BSTR url) = 0;
    virtual HRESULT STDMETHODCALLTYPE cycleOnlineMainMenu() = 0;
    virtual HRESULT STDMETHODCALLTYPE cycleLogOut() = 0;
    virtual HRESULT STDMETHODCALLTYPE cycleLogIn(BSTR user, BSTR pass) = 0;
    virtual HRESULT STDMETHODCALLTYPE cycleCreateAccount(BSTR user, BSTR pass, BSTR email) = 0;
    virtual HRESULT STDMETHODCALLTYPE cycleVersionMismatch() = 0;
    virtual HRESULT STDMETHODCALLTYPE cycleSetAlternateText(BSTR text) = 0;
    virtual HRESULT STDMETHODCALLTYPE cycleNavDelayTimerExpired() = 0;
    virtual HRESULT STDMETHODCALLTYPE cycleMinimize() = 0;
    virtual HRESULT STDMETHODCALLTYPE cycleClose() = 0;
    virtual HRESULT STDMETHODCALLTYPE cyclePageLoading(int loading) = 0;
    virtual HRESULT STDMETHODCALLTYPE cycleDataReceived(BSTR url, unsigned char *data, int len) = 0;
    virtual HRESULT STDMETHODCALLTYPE cycleDataFailed(BSTR url) = 0;
    virtual HRESULT STDMETHODCALLTYPE cycleCloseLauncher() = 0;
    virtual HRESULT STDMETHODCALLTYPE cycleBackgroundMovieEnabled() = 0;
};
