#pragma once
// Stub — WOL browser COM interfaces not used in D3D11 remaster.
// Original was generated by MIDL from BrowserEngine.idl.
#include <unknwn.h>

DEFINE_GUID(IID_IFEBrowserEngine, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0);

struct IFEBrowserEngine : public IUnknown
{
    virtual HRESULT STDMETHODCALLTYPE pakOpen(BSTR, unsigned char**, int*) = 0;
};
