# Auto-generated from z_generals.vcxproj
set(GAME_SOURCES
    pch.cpp
    resources/gitinfo/gitinfo.cpp
    Core/GameEngineDevice/Source/MilesAudioDevice/MilesAudioManager.cpp
    Core/GameEngineDevice/Source/VideoDevice/Bink/BinkVideoPlayer.cpp
    Core/GameEngineDevice/Source/VideoDevice/FFmpeg/FFmpegFile.cpp
    Core/GameEngineDevice/Source/VideoDevice/FFmpeg/FFmpegVideoPlayer.cpp
    Core/GameEngineDevice/Source/W3DDevice/GameClient/Drawable/Draw/W3DDebrisDraw.cpp
    Core/GameEngineDevice/Source/W3DDevice/GameClient/Drawable/Draw/W3DDefaultDraw.cpp
    Core/GameEngineDevice/Source/W3DDevice/GameClient/Drawable/Draw/W3DDependencyModelDraw.cpp
    Core/GameEngineDevice/Source/W3DDevice/GameClient/Drawable/Draw/W3DLaserDraw.cpp
    Core/GameEngineDevice/Source/W3DDevice/GameClient/Drawable/Draw/W3DModelDraw.cpp
    Core/GameEngineDevice/Source/W3DDevice/GameClient/Drawable/Draw/W3DOverlordAircraftDraw.cpp
    Core/GameEngineDevice/Source/W3DDevice/GameClient/Drawable/Draw/W3DOverlordTankDraw.cpp
    Core/GameEngineDevice/Source/W3DDevice/GameClient/Drawable/Draw/W3DOverlordTruckDraw.cpp
    Core/GameEngineDevice/Source/W3DDevice/GameClient/Drawable/Draw/W3DPoliceCarDraw.cpp
    Core/GameEngineDevice/Source/W3DDevice/GameClient/Drawable/Draw/W3DProjectileStreamDraw.cpp
    Core/GameEngineDevice/Source/W3DDevice/GameClient/Drawable/Draw/W3DPropDraw.cpp
    Core/GameEngineDevice/Source/W3DDevice/GameClient/Drawable/Draw/W3DRopeDraw.cpp
    Core/GameEngineDevice/Source/W3DDevice/GameClient/Drawable/Draw/W3DScienceModelDraw.cpp
    Core/GameEngineDevice/Source/W3DDevice/GameClient/Drawable/Draw/W3DSupplyDraw.cpp
    Core/GameEngineDevice/Source/W3DDevice/GameClient/Drawable/Draw/W3DTankDraw.cpp
    Core/GameEngineDevice/Source/W3DDevice/GameClient/Drawable/Draw/W3DTankTruckDraw.cpp
    Core/GameEngineDevice/Source/W3DDevice/GameClient/Drawable/Draw/W3DTracerDraw.cpp
    Core/GameEngineDevice/Source/W3DDevice/GameClient/Drawable/Draw/W3DTreeDraw.cpp
    Core/GameEngineDevice/Source/W3DDevice/GameClient/Drawable/Draw/W3DTruckDraw.cpp
    Core/GameEngineDevice/Source/W3DDevice/GameClient/TileData.cpp
    Core/GameEngineDevice/Source/W3DDevice/GameClient/WorldHeightMap.cpp
    Core/GameEngineDevice/Source/Win32Device/Common/Win32BIGFile.cpp
    Core/GameEngineDevice/Source/Win32Device/Common/Win32BIGFileSystem.cpp
    Core/GameEngineDevice/Source/Win32Device/Common/Win32LocalFile.cpp
    Core/GameEngineDevice/Source/Win32Device/Common/Win32LocalFileSystem.cpp
    Core/GameEngineDevice/Source/Win32Device/GameClient/Win32Mouse.cpp
    Core/GameEngine/Source/Common/AddonCompat.cpp
    Core/GameEngine/Source/Common/Audio/AudioEventRTS.cpp
    Core/GameEngine/Source/Common/Audio/AudioRequest.cpp
    Core/GameEngine/Source/Common/Audio/DynamicAudioEventInfo.cpp
    Core/GameEngine/Source/Common/Audio/GameAudio.cpp
    Core/GameEngine/Source/Common/Audio/GameMusic.cpp
    Core/GameEngine/Source/Common/Audio/GameSounds.cpp
    Core/GameEngine/Source/Common/CosmeticsCache.cpp
    Core/GameEngine/Source/Common/CRCDebug.cpp
    Core/GameEngine/Source/Common/Telemetry.cpp
    extern/sqlite3/sqlite3.c
    Core/GameEngine/Source/Common/FramePacer.cpp
    Core/GameEngine/Source/Common/FrameRateLimit.cpp
    Core/GameEngine/Source/Common/SearchPaths.cpp
    Core/GameEngine/Source/Common/GameUtility.cpp
    Core/GameEngine/Source/Common/INI/INI.cpp
    Core/GameEngine/Source/Common/INI/INIAudioEventInfo.cpp
    Core/GameEngine/Source/Common/INI/INIMiscAudio.cpp
    Core/GameEngine/Source/Common/INI/INIVideo.cpp
    Core/GameEngine/Source/Common/OptionPreferences.cpp
    Core/GameEngine/Source/Common/RandomValue.cpp
    Core/GameEngine/Source/Common/ReplaySimulation.cpp
    Core/GameEngine/Source/Common/System/ArchiveFile.cpp
    Core/GameEngine/Source/Common/System/ArchiveFileSystem.cpp
    Core/GameEngine/Source/Common/System/AsciiString.cpp
    Core/GameEngine/Source/Common/System/Debug.cpp
    Core/GameEngine/Source/Common/System/File.cpp
    Core/GameEngine/Source/Common/System/FileSystem.cpp
    Core/GameEngine/Source/Common/System/GameCommon.cpp
    Core/GameEngine/Source/Common/System/GameMemory.cpp
    Core/GameEngine/Source/Common/System/GameMemoryInit.cpp
    Core/GameEngine/Source/Common/System/GameType.cpp
    Core/GameEngine/Source/Common/System/LocalFile.cpp
    Core/GameEngine/Source/Common/System/LocalFileSystem.cpp
    Core/GameEngine/Source/Common/System/MiniDumper.cpp
    Core/GameEngine/Source/Common/System/ObjectStatusTypes.cpp
    Core/GameEngine/Source/Common/System/RAMFile.cpp
    Core/GameEngine/Source/Common/System/Radar.cpp
    Core/GameEngine/Source/Common/System/Snapshot.cpp
    Core/GameEngine/Source/Common/System/StreamingArchiveFile.cpp
    Core/GameEngine/Source/Common/System/SubsystemInterface.cpp
    Core/GameEngine/Source/Common/System/UnicodeString.cpp
    Core/GameEngine/Source/Common/System/Xfer.cpp
    Core/GameEngine/Source/Common/System/XferCRC.cpp
    Core/GameEngine/Source/Common/System/XferLoad.cpp
    Core/GameEngine/Source/Common/System/XferSave.cpp
    Core/GameEngine/Source/Common/UserPreferences.cpp
    Core/GameEngine/Source/Common/WorkerProcess.cpp
    Core/GameEngine/Source/Common/crc.cpp
    Core/GameEngine/Source/GameClient/ClientInstance.cpp
    Core/GameEngine/Source/GameClient/Color.cpp
    Core/GameEngine/Source/GameClient/Credits.cpp
    Core/GameEngine/Source/GameClient/DisplayString.cpp
    Core/GameEngine/Source/GameClient/DisplayStringManager.cpp
    Core/GameEngine/Source/GameClient/DrawGroupInfo.cpp
    Core/GameEngine/Source/GameClient/FXList.cpp
    Core/GameEngine/Source/GameClient/GUI/ChallengeGenerals.cpp
    Core/GameEngine/Source/GameClient/GUI/GameFont.cpp
    Core/GameEngine/Source/GameClient/GUI/GameWindow.cpp
    Core/GameEngine/Source/GameClient/GUI/GameWindowGlobal.cpp
    Core/GameEngine/Source/GameClient/GUI/GameWindowTransitions.cpp
    Core/GameEngine/Source/GameClient/GUI/HeaderTemplate.cpp
    Core/GameEngine/Source/GameClient/GUI/IMEManager.cpp
    Core/GameEngine/Source/GameClient/GUI/LoadScreen.cpp
    Core/GameEngine/Source/GameClient/GUI/ProcessAnimateWindow.cpp
    Core/GameEngine/Source/GameClient/GUI/WinInstanceData.cpp
    Core/GameEngine/Source/GameClient/GUI/WindowLayout.cpp
    Core/GameEngine/Source/GameClient/GUI/WindowVideoManager.cpp
    Core/GameEngine/Source/GameClient/GameText.cpp
    Core/GameEngine/Source/GameClient/GlobalLanguage.cpp
    Core/GameEngine/Source/GameClient/GraphDraw.cpp
    Core/GameEngine/Source/GameClient/Input/Keyboard.cpp
    Core/GameEngine/Source/GameClient/Input/Mouse.cpp
    Core/GameEngine/Source/GameClient/LanguageFilter.cpp
    Core/GameEngine/Source/GameClient/Line2D.cpp
    Core/GameEngine/Source/GameClient/MapUtil.cpp
    Core/GameEngine/Source/GameClient/ParabolicEase.cpp
    Core/GameEngine/Source/GameClient/RadiusDecal.cpp
    Core/GameEngine/Source/GameClient/SelectionInfo.cpp
    Core/GameEngine/Source/GameClient/Snow.cpp
    Core/GameEngine/Source/GameClient/Statistics.cpp
    Core/GameEngine/Source/GameClient/System/Debug/AudioDebugDisplay.cpp
    Core/GameEngine/Source/GameClient/System/ParticleSys.cpp
    Core/GameEngine/Source/GameClient/System/Smudge.cpp
    Core/GameEngine/Source/GameClient/Terrain/TerrainRoads.cpp
    Core/GameEngine/Source/GameClient/Terrain/TerrainVisual.cpp
    Core/GameEngine/Source/GameClient/VideoPlayer.cpp
    Core/GameEngine/Source/GameClient/VideoStream.cpp
    Core/GameEngine/Source/GameClient/View.cpp
    Core/GameEngine/Source/GameClient/Water.cpp
    Core/GameEngine/Source/GameNetwork/Connection.cpp
    Core/GameEngine/Source/GameNetwork/ConnectionManager.cpp
    Core/GameEngine/Source/GameNetwork/DisconnectManager.cpp
    Core/GameEngine/Source/GameNetwork/DownloadManager.cpp
    Core/GameEngine/Source/GameNetwork/FileTransfer.cpp
    Core/GameEngine/Source/GameNetwork/FirewallHelper.cpp
    Core/GameEngine/Source/GameNetwork/FrameData.cpp
    Core/GameEngine/Source/GameNetwork/FrameDataManager.cpp
    Core/GameEngine/Source/GameNetwork/FrameMetrics.cpp
    Core/GameEngine/Source/GameNetwork/GameInfo.cpp
    Core/GameEngine/Source/GameNetwork/GameMessageParser.cpp
    Core/GameEngine/Source/GameNetwork/GameSpyStubs.cpp
    Core/GameEngine/Source/GameNetwork/IPEnumeration.cpp
    Core/GameEngine/Source/GameNetwork/LANAPI.cpp
    Core/GameEngine/Source/GameNetwork/LANAPICallbacks.cpp
    Core/GameEngine/Source/GameNetwork/RestClient.cpp
    Core/GameEngine/Source/GameNetwork/LANAPIhandlers.cpp
    Core/GameEngine/Source/GameNetwork/LANGameInfo.cpp
    Core/GameEngine/Source/GameNetwork/NetCommandList.cpp
    Core/GameEngine/Source/GameNetwork/NetCommandMsg.cpp
    Core/GameEngine/Source/GameNetwork/NetCommandRef.cpp
    Core/GameEngine/Source/GameNetwork/NetCommandWrapperList.cpp
    Core/GameEngine/Source/GameNetwork/NetMessageStream.cpp
    Core/GameEngine/Source/GameNetwork/NetPacket.cpp
    Core/GameEngine/Source/GameNetwork/Network.cpp
    Core/GameEngine/Source/GameNetwork/NetworkUtil.cpp
    Core/GameEngine/Source/GameNetwork/Transport.cpp
    Core/GameEngine/Source/GameNetwork/User.cpp
    Core/GameEngine/Source/GameNetwork/WOLBrowser/WebBrowser.cpp
    Core/GameEngine/Source/GameNetwork/udp.cpp
    Core/Libraries/Source/Compression/CompressionManager.cpp
    Core/Libraries/Source/Compression/EAC/btreeabout.cpp
    Core/Libraries/Source/Compression/EAC/btreedecode.cpp
    Core/Libraries/Source/Compression/EAC/btreeencode.cpp
    Core/Libraries/Source/Compression/EAC/huffabout.cpp
    Core/Libraries/Source/Compression/EAC/huffdecode.cpp
    Core/Libraries/Source/Compression/EAC/huffencode.cpp
    Core/Libraries/Source/Compression/EAC/refabout.cpp
    Core/Libraries/Source/Compression/EAC/refdecode.cpp
    Core/Libraries/Source/Compression/EAC/refencode.cpp
    Core/Libraries/Source/Compression/LZHCompress/NoxCompress.cpp
    Core/Libraries/Source/WWVegas/WW3D2/aabtree.cpp
    Core/Libraries/Source/WWVegas/WW3D2/agg_def.cpp
    Core/Libraries/Source/WWVegas/WW3D2/animatedsoundmgr.cpp
    Core/Libraries/Source/WWVegas/WW3D2/assetstatus.cpp
    Core/Libraries/Source/WWVegas/WW3D2/collect.cpp
    Core/Libraries/Source/WWVegas/WW3D2/coltest.cpp
    Core/Libraries/Source/WWVegas/WW3D2/composite.cpp
    Core/Libraries/Source/WWVegas/WW3D2/dazzle.cpp
    Core/Libraries/Source/WWVegas/WW3D2/distlod.cpp
    Core/Libraries/Source/WWVegas/WW3D2/hanim.cpp
    Core/Libraries/Source/WWVegas/WW3D2/hcanim.cpp
    Core/Libraries/Source/WWVegas/WW3D2/hmdldef.cpp
    Core/Libraries/Source/WWVegas/WW3D2/htree.cpp
    Core/Libraries/Source/WWVegas/WW3D2/intersec.cpp
    Core/Libraries/Source/WWVegas/WW3D2/layer.cpp
    Core/Libraries/Source/WWVegas/WW3D2/linegrp.cpp
    Core/Libraries/Source/WWVegas/WW3D2/matinfo.cpp
    Core/Libraries/Source/WWVegas/WW3D2/meshdam.cpp
    Core/Libraries/Source/WWVegas/WW3D2/metalmap.cpp
    Core/Libraries/Source/WWVegas/WW3D2/part_buf.cpp
    Core/Libraries/Source/WWVegas/WW3D2/part_emt.cpp
    Core/Libraries/Source/WWVegas/WW3D2/part_ldr.cpp
    Core/Libraries/Source/WWVegas/WW3D2/pivot.cpp
    Core/Libraries/Source/WWVegas/WW3D2/pointgr.cpp
    Core/Libraries/Source/WWVegas/WW3D2/polyinfo.cpp
    Core/Libraries/Source/WWVegas/WW3D2/predlod.cpp
    Core/Libraries/Source/WWVegas/WW3D2/prim_anim.cpp
    Core/Libraries/Source/WWVegas/WW3D2/proto.cpp
    Core/Libraries/Source/WWVegas/WW3D2/renderobjectrecycler.cpp
    Core/Libraries/Source/WWVegas/WW3D2/rendobj.cpp
    Core/Libraries/Source/WWVegas/WW3D2/snappts.cpp
    Core/Libraries/Source/WWVegas/WW3D2/soundrobj.cpp
    Core/Libraries/Source/WWVegas/WW3D2/stripoptimizer.cpp
    Core/Libraries/Source/WWVegas/WW3D2/w3d_dep.cpp
    Core/Libraries/Source/WWVegas/WW3D2/w3d_util.cpp
    Core/Libraries/Source/WWVegas/WW3D2/w3dexclusionlist.cpp
    Core/Libraries/Source/WWVegas/WWAudio/AudibleSound.cpp
    Core/Libraries/Source/WWVegas/WWAudio/AudioSaveLoad.cpp
    Core/Libraries/Source/WWVegas/WWAudio/FilteredSound.cpp
    Core/Libraries/Source/WWVegas/WWAudio/Listener.cpp
    Core/Libraries/Source/WWVegas/WWAudio/LogicalListener.cpp
    Core/Libraries/Source/WWVegas/WWAudio/LogicalSound.cpp
    Core/Libraries/Source/WWVegas/WWAudio/Sound3D.cpp
    Core/Libraries/Source/WWVegas/WWAudio/SoundBuffer.cpp
    Core/Libraries/Source/WWVegas/WWAudio/SoundPseudo3D.cpp
    Core/Libraries/Source/WWVegas/WWAudio/SoundScene.cpp
    Core/Libraries/Source/WWVegas/WWAudio/SoundSceneObj.cpp
    Core/Libraries/Source/WWVegas/WWAudio/Threads.cpp
    Core/Libraries/Source/WWVegas/WWAudio/Utils.cpp
    Core/Libraries/Source/WWVegas/WWAudio/WWAudio.cpp
    Core/Libraries/Source/WWVegas/WWAudio/listenerhandle.cpp
    Core/Libraries/Source/WWVegas/WWAudio/sound2dhandle.cpp
    Core/Libraries/Source/WWVegas/WWAudio/sound3dhandle.cpp
    Core/Libraries/Source/WWVegas/WWAudio/soundhandle.cpp
    Core/Libraries/Source/WWVegas/WWAudio/soundstreamhandle.cpp
    Core/Libraries/Source/WWVegas/WWDebug/wwdebug.cpp
    Core/Libraries/Source/WWVegas/WWDebug/wwmemlog.cpp
    Core/Libraries/Source/WWVegas/WWDebug/wwprofile.cpp
    Core/Libraries/Source/WWVegas/WWDownload/Download.cpp
    Core/Libraries/Source/WWVegas/WWDownload/FTP.cpp
    Core/Libraries/Source/WWVegas/WWDownload/registry.cpp
    Core/Libraries/Source/WWVegas/WWDownload/urlBuilder.cpp
    Core/Libraries/Source/WWVegas/WWLib/DbgHelpGuard.cpp
    Core/Libraries/Source/WWVegas/WWLib/DbgHelpLoader.cpp
    Core/Libraries/Source/WWVegas/WWLib/Except.cpp
    Core/Libraries/Source/WWVegas/WWLib/FastAllocator.cpp
    Core/Libraries/Source/WWVegas/WWLib/TARGA.cpp
    Core/Libraries/Source/WWVegas/WWLib/WWCOMUtil.cpp
    Core/Libraries/Source/WWVegas/WWLib/argv.cpp
    Core/Libraries/Source/WWVegas/WWLib/b64pipe.cpp
    Core/Libraries/Source/WWVegas/WWLib/b64straw.cpp
    Core/Libraries/Source/WWVegas/WWLib/base64.cpp
    Core/Libraries/Source/WWVegas/WWLib/buff.cpp
    Core/Libraries/Source/WWVegas/WWLib/bufffile.cpp
    Core/Libraries/Source/WWVegas/WWLib/chunkio.cpp
    Core/Libraries/Source/WWVegas/WWLib/cpudetect.cpp
    Core/Libraries/Source/WWVegas/WWLib/crc.cpp
    Core/Libraries/Source/WWVegas/WWLib/cstraw.cpp
    Core/Libraries/Source/WWVegas/WWLib/ffactory.cpp
    Core/Libraries/Source/WWVegas/WWLib/gcd_lcm.cpp
    Core/Libraries/Source/WWVegas/WWLib/hash.cpp
    Core/Libraries/Source/WWVegas/WWLib/ini.cpp
    Core/Libraries/Source/WWVegas/WWLib/jshell.cpp
    Core/Libraries/Source/WWVegas/WWLib/mpu.cpp
    Core/Libraries/Source/WWVegas/WWLib/multilist.cpp
    Core/Libraries/Source/WWVegas/WWLib/mutex.cpp
    Core/Libraries/Source/WWVegas/WWLib/nstrdup.cpp
    Core/Libraries/Source/WWVegas/WWLib/pipe.cpp
    Core/Libraries/Source/WWVegas/WWLib/ramfile.cpp
    Core/Libraries/Source/WWVegas/WWLib/random.cpp
    Core/Libraries/Source/WWVegas/WWLib/rawfile.cpp
    Core/Libraries/Source/WWVegas/WWLib/rcfile.cpp
    Core/Libraries/Source/WWVegas/WWLib/readline.cpp
    Core/Libraries/Source/WWVegas/WWLib/realcrc.cpp
    Core/Libraries/Source/WWVegas/WWLib/refcount.cpp
    Core/Libraries/Source/WWVegas/WWLib/registry.cpp
    Core/Libraries/Source/WWVegas/WWLib/slnode.cpp
    Core/Libraries/Source/WWVegas/WWLib/stimer.cpp
    Core/Libraries/Source/WWVegas/WWLib/straw.cpp
    Core/Libraries/Source/WWVegas/WWLib/strtok_r.cpp
    Core/Libraries/Source/WWVegas/WWLib/systimer.cpp
    Core/Libraries/Source/WWVegas/WWLib/textfile.cpp
    Core/Libraries/Source/WWVegas/WWLib/tgatodxt.cpp
    Core/Libraries/Source/WWVegas/WWLib/thread.cpp
    Core/Libraries/Source/WWVegas/WWLib/trim.cpp
    Core/Libraries/Source/WWVegas/WWLib/vector.cpp
    Core/Libraries/Source/WWVegas/WWLib/verchk.cpp
    Core/Libraries/Source/WWVegas/WWLib/widestring.cpp
    Core/Libraries/Source/WWVegas/WWLib/wwfile.cpp
    Core/Libraries/Source/WWVegas/WWLib/wwstring.cpp
    Core/Libraries/Source/WWVegas/WWLib/xpipe.cpp
    Core/Libraries/Source/WWVegas/WWLib/xstraw.cpp
    Core/Libraries/Source/WWVegas/WWMath/aabox.cpp
    Core/Libraries/Source/WWVegas/WWMath/aabtreecull.cpp
    Core/Libraries/Source/WWVegas/WWMath/cardinalspline.cpp
    Core/Libraries/Source/WWVegas/WWMath/catmullromspline.cpp
    Core/Libraries/Source/WWVegas/WWMath/colmath.cpp
    Core/Libraries/Source/WWVegas/WWMath/colmathaabox.cpp
    Core/Libraries/Source/WWVegas/WWMath/colmathaabtri.cpp
    Core/Libraries/Source/WWVegas/WWMath/colmathfrustum.cpp
    Core/Libraries/Source/WWVegas/WWMath/colmathline.cpp
    Core/Libraries/Source/WWVegas/WWMath/colmathobbobb.cpp
    Core/Libraries/Source/WWVegas/WWMath/colmathobbox.cpp
    Core/Libraries/Source/WWVegas/WWMath/colmathobbtri.cpp
    Core/Libraries/Source/WWVegas/WWMath/colmathplane.cpp
    Core/Libraries/Source/WWVegas/WWMath/colmathsphere.cpp
    Core/Libraries/Source/WWVegas/WWMath/cullsys.cpp
    Core/Libraries/Source/WWVegas/WWMath/curve.cpp
    Core/Libraries/Source/WWVegas/WWMath/euler.cpp
    Core/Libraries/Source/WWVegas/WWMath/frustum.cpp
    Core/Libraries/Source/WWVegas/WWMath/gridcull.cpp
    Core/Libraries/Source/WWVegas/WWMath/hermitespline.cpp
    Core/Libraries/Source/WWVegas/WWMath/lineseg.cpp
    Core/Libraries/Source/WWVegas/WWMath/lookuptable.cpp
    Core/Libraries/Source/WWVegas/WWMath/matrix3.cpp
    Core/Libraries/Source/WWVegas/WWMath/matrix3d.cpp
    Core/Libraries/Source/WWVegas/WWMath/matrix4.cpp
    Core/Libraries/Source/WWVegas/WWMath/obbox.cpp
    Core/Libraries/Source/WWVegas/WWMath/ode.cpp
    Core/Libraries/Source/WWVegas/WWMath/pot.cpp
    Core/Libraries/Source/WWVegas/WWMath/quat.cpp
    Core/Libraries/Source/WWVegas/WWMath/tcbspline.cpp
    Core/Libraries/Source/WWVegas/WWMath/tri.cpp
    Core/Libraries/Source/WWVegas/WWMath/v3_rnd.cpp
    Core/Libraries/Source/WWVegas/WWMath/vehiclecurve.cpp
    Core/Libraries/Source/WWVegas/WWMath/vp.cpp
    Core/Libraries/Source/WWVegas/WWMath/wwmath.cpp
    Core/Libraries/Source/WWVegas/WWSaveLoad/definition.cpp
    Core/Libraries/Source/WWVegas/WWSaveLoad/definitionfactory.cpp
    Core/Libraries/Source/WWVegas/WWSaveLoad/definitionfactorymgr.cpp
    Core/Libraries/Source/WWVegas/WWSaveLoad/definitionmgr.cpp
    Core/Libraries/Source/WWVegas/WWSaveLoad/parameter.cpp
    Core/Libraries/Source/WWVegas/WWSaveLoad/persistfactory.cpp
    Core/Libraries/Source/WWVegas/WWSaveLoad/pointerremap.cpp
    Core/Libraries/Source/WWVegas/WWSaveLoad/saveload.cpp
    Core/Libraries/Source/WWVegas/WWSaveLoad/saveloadstatus.cpp
    Core/Libraries/Source/WWVegas/WWSaveLoad/saveloadsubsystem.cpp
    Core/Libraries/Source/WWVegas/WWSaveLoad/twiddler.cpp
    Core/Libraries/Source/WWVegas/WWSaveLoad/wwsaveload.cpp
    Core/Libraries/Source/debug/debug_cmd.cpp
    Core/Libraries/Source/debug/debug_debug.cpp
    Core/Libraries/Source/debug/debug_except.cpp
    Core/Libraries/Source/debug/debug_getdefaultcommands.cpp
    Core/Libraries/Source/debug/debug_internal.cpp
    Core/Libraries/Source/debug/debug_io_con.cpp
    Core/Libraries/Source/debug/debug_io_flat.cpp
    Core/Libraries/Source/debug/debug_io_net.cpp
    Core/Libraries/Source/debug/debug_io_ods.cpp
    Core/Libraries/Source/debug/debug_stack.cpp
    Core/Libraries/Source/profile/profile.cpp
    Core/Libraries/Source/profile/profile_cmd.cpp
    Core/Libraries/Source/profile/profile_funclevel.cpp
    Core/Libraries/Source/profile/profile_highlevel.cpp
    Core/Libraries/Source/profile/profile_result.cpp
    GeneralsMD/Code/GameEngineDevice/Source/Stubs/AudioVideoStubs.cpp
    GeneralsMD/Code/GameEngineDevice/Source/W3DDevice/Common/System/W3DFunctionLexicon.cpp
    GeneralsMD/Code/GameEngineDevice/Source/W3DDevice/Common/Thing/W3DModuleFactory.cpp
    GeneralsMD/Code/GameEngineDevice/Source/W3DDevice/Common/Thing/W3DThingFactory.cpp
    GeneralsMD/Code/GameEngineDevice/Source/W3DDevice/Common/W3DConvert.cpp
    GeneralsMD/Code/GameEngineDevice/Source/W3DDevice/GameClient/D3D11Shims.cpp
    GeneralsMD/Code/GameEngineDevice/Source/W3DDevice/GameClient/GUI/GUICallbacks/W3DControlBar.cpp
    GeneralsMD/Code/GameEngineDevice/Source/W3DDevice/GameClient/GUI/GUICallbacks/W3DMOTD.cpp
    GeneralsMD/Code/GameEngineDevice/Source/W3DDevice/GameClient/GUI/GUICallbacks/W3DMainMenu.cpp
    GeneralsMD/Code/GameEngineDevice/Source/W3DDevice/GameClient/GUI/Gadget/W3DCheckBox.cpp
    GeneralsMD/Code/GameEngineDevice/Source/W3DDevice/GameClient/GUI/Gadget/W3DComboBox.cpp
    GeneralsMD/Code/GameEngineDevice/Source/W3DDevice/GameClient/GUI/Gadget/W3DHorizontalSlider.cpp
    GeneralsMD/Code/GameEngineDevice/Source/W3DDevice/GameClient/GUI/Gadget/W3DListBox.cpp
    GeneralsMD/Code/GameEngineDevice/Source/W3DDevice/GameClient/GUI/Gadget/W3DProgressBar.cpp
    GeneralsMD/Code/GameEngineDevice/Source/W3DDevice/GameClient/GUI/Gadget/W3DPushButton.cpp
    GeneralsMD/Code/GameEngineDevice/Source/W3DDevice/GameClient/GUI/Gadget/W3DRadioButton.cpp
    GeneralsMD/Code/GameEngineDevice/Source/W3DDevice/GameClient/GUI/Gadget/W3DStaticText.cpp
    GeneralsMD/Code/GameEngineDevice/Source/W3DDevice/GameClient/GUI/Gadget/W3DTabControl.cpp
    GeneralsMD/Code/GameEngineDevice/Source/W3DDevice/GameClient/GUI/Gadget/W3DTextEntry.cpp
    GeneralsMD/Code/GameEngineDevice/Source/W3DDevice/GameClient/GUI/Gadget/W3DVerticalSlider.cpp
    GeneralsMD/Code/GameEngineDevice/Source/W3DDevice/GameClient/GUI/W3DGameWindow.cpp
    GeneralsMD/Code/GameEngineDevice/Source/W3DDevice/GameClient/GUI/W3DGameWindowManager.cpp
    GeneralsMD/Code/GameEngineDevice/Source/W3DDevice/GameClient/ImageCache.cpp
    GeneralsMD/Code/GameEngineDevice/Source/W3DDevice/GameClient/ModelRenderer.cpp
    GeneralsMD/Code/GameEngineDevice/Source/W3DDevice/GameClient/TerrainRenderer.cpp
    GeneralsMD/Code/GameEngineDevice/Source/W3DDevice/GameClient/W3DAssetManagerLite.cpp
    GeneralsMD/Code/GameEngineDevice/Source/W3DDevice/GameClient/W3DDisplay.cpp
    GeneralsMD/Code/GameEngineDevice/Source/W3DDevice/GameClient/RoadGeometry.cpp
    GeneralsMD/Code/GameEngineDevice/Source/W3DDevice/GameClient/W3DDisplayString.cpp
    GeneralsMD/Code/GameEngineDevice/Source/W3DDevice/GameClient/W3DDisplayStringManager.cpp
    GeneralsMD/Code/GameEngineDevice/Source/W3DDevice/GameClient/W3DDynamicLight.cpp
    GeneralsMD/Code/GameEngineDevice/Source/W3DDevice/GameClient/W3DFileSystem.cpp
    GeneralsMD/Code/GameEngineDevice/Source/W3DDevice/GameClient/W3DGameClient.cpp
    GeneralsMD/Code/GameEngineDevice/Source/W3DDevice/GameClient/W3DPoly.cpp
    GeneralsMD/Code/GameEngineDevice/Source/W3DDevice/GameClient/Shadow/W3DShadow.cpp
    GeneralsMD/Code/GameEngineDevice/Source/W3DDevice/GameClient/Shadow/W3DProjectedShadow.cpp
    GeneralsMD/Code/GameEngineDevice/Source/W3DDevice/GameClient/Shadow/W3DBufferManager.cpp
    GeneralsMD/Code/GameEngineDevice/Source/W3DDevice/GameClient/WW3DAssetCompat.cpp
    GeneralsMD/Code/GameEngineDevice/Source/W3DDevice/GameClient/WW3DMeshCompat.cpp
    GeneralsMD/Code/GameEngineDevice/Source/W3DDevice/GameLogic/W3DGameLogic.cpp
    GeneralsMD/Code/GameEngineDevice/Source/W3DDevice/GameLogic/W3DGhostObject.cpp
    GeneralsMD/Code/GameEngineDevice/Source/Win32Device/Common/Win32GameEngine.cpp
    GeneralsMD/Code/GameEngineDevice/Source/Win32Device/Common/Win32OSDisplay.cpp
    GeneralsMD/Code/GameEngine/Source/Common/Bezier/BezFwdIterator.cpp
    GeneralsMD/Code/GameEngine/Source/Common/Bezier/BezierSegment.cpp
    GeneralsMD/Code/GameEngine/Source/Common/BitFlags.cpp
    GeneralsMD/Code/GameEngine/Source/Common/CommandLine.cpp
    GeneralsMD/Code/GameEngine/Source/Common/DamageFX.cpp
    GeneralsMD/Code/GameEngine/Source/Common/Dict.cpp
    GeneralsMD/Code/GameEngine/Source/Common/DiscreteCircle.cpp
    GeneralsMD/Code/GameEngine/Source/Common/GameEngine.cpp
    GeneralsMD/Code/GameEngine/Source/Common/GameLOD.cpp
    GeneralsMD/Code/GameEngine/Source/Common/GameMain.cpp
    GeneralsMD/Code/GameEngine/Source/Common/GlobalData.cpp
    GeneralsMD/Code/GameEngine/Source/Common/INI/INIAiData.cpp
    GeneralsMD/Code/GameEngine/Source/Common/INI/INIAnimation.cpp
    GeneralsMD/Code/GameEngine/Source/Common/INI/INICommandButton.cpp
    GeneralsMD/Code/GameEngine/Source/Common/INI/INICommandSet.cpp
    GeneralsMD/Code/GameEngine/Source/Common/INI/INIControlBarScheme.cpp
    GeneralsMD/Code/GameEngine/Source/Common/INI/INICrate.cpp
    GeneralsMD/Code/GameEngine/Source/Common/INI/INIDamageFX.cpp
    GeneralsMD/Code/GameEngine/Source/Common/INI/INIDrawGroupInfo.cpp
    GeneralsMD/Code/GameEngine/Source/Common/INI/INIGameData.cpp
    GeneralsMD/Code/GameEngine/Source/Common/INI/INIMapCache.cpp
    GeneralsMD/Code/GameEngine/Source/Common/INI/INIMapData.cpp
    GeneralsMD/Code/GameEngine/Source/Common/INI/INIMappedImage.cpp
    GeneralsMD/Code/GameEngine/Source/Common/INI/INIModel.cpp
    GeneralsMD/Code/GameEngine/Source/Common/INI/INIMultiplayer.cpp
    GeneralsMD/Code/GameEngine/Source/Common/INI/INIObject.cpp
    GeneralsMD/Code/GameEngine/Source/Common/INI/INIParticleSys.cpp
    GeneralsMD/Code/GameEngine/Source/Common/INI/INISpecialPower.cpp
    GeneralsMD/Code/GameEngine/Source/Common/INI/INITerrain.cpp
    GeneralsMD/Code/GameEngine/Source/Common/INI/INITerrainBridge.cpp
    GeneralsMD/Code/GameEngine/Source/Common/INI/INITerrainRoad.cpp
    GeneralsMD/Code/GameEngine/Source/Common/INI/INIUpgrade.cpp
    GeneralsMD/Code/GameEngine/Source/Common/INI/INIWater.cpp
    GeneralsMD/Code/GameEngine/Source/Common/INI/INIWeapon.cpp
    GeneralsMD/Code/GameEngine/Source/Common/INI/INIWebpageURL.cpp
    GeneralsMD/Code/GameEngine/Source/Common/Language.cpp
    GeneralsMD/Code/GameEngine/Source/Common/MessageStream.cpp
    GeneralsMD/Code/GameEngine/Source/Common/MiniLog.cpp
    GeneralsMD/Code/GameEngine/Source/Common/MultiplayerSettings.cpp
    GeneralsMD/Code/GameEngine/Source/Common/NameKeyGenerator.cpp
    GeneralsMD/Code/GameEngine/Source/Common/PartitionSolver.cpp
    GeneralsMD/Code/GameEngine/Source/Common/PerfTimer.cpp
    GeneralsMD/Code/GameEngine/Source/Common/RTS/AcademyStats.cpp
    GeneralsMD/Code/GameEngine/Source/Common/RTS/ActionManager.cpp
    GeneralsMD/Code/GameEngine/Source/Common/RTS/Energy.cpp
    GeneralsMD/Code/GameEngine/Source/Common/RTS/Handicap.cpp
    GeneralsMD/Code/GameEngine/Source/Common/RTS/MissionStats.cpp
    GeneralsMD/Code/GameEngine/Source/Common/RTS/Money.cpp
    GeneralsMD/Code/GameEngine/Source/Common/RTS/Player.cpp
    GeneralsMD/Code/GameEngine/Source/Common/RTS/PlayerList.cpp
    GeneralsMD/Code/GameEngine/Source/Common/RTS/PlayerTemplate.cpp
    GeneralsMD/Code/GameEngine/Source/Common/RTS/ProductionPrerequisite.cpp
    GeneralsMD/Code/GameEngine/Source/Common/RTS/ResourceGatheringManager.cpp
    GeneralsMD/Code/GameEngine/Source/Common/RTS/Science.cpp
    GeneralsMD/Code/GameEngine/Source/Common/RTS/ScoreKeeper.cpp
    GeneralsMD/Code/GameEngine/Source/Common/RTS/SpecialPower.cpp
    GeneralsMD/Code/GameEngine/Source/Common/RTS/Team.cpp
    GeneralsMD/Code/GameEngine/Source/Common/RTS/TunnelTracker.cpp
    GeneralsMD/Code/GameEngine/Source/Common/Recorder.cpp
    GeneralsMD/Code/GameEngine/Source/Common/SkirmishBattleHonors.cpp
    GeneralsMD/Code/GameEngine/Source/Common/StateMachine.cpp
    GeneralsMD/Code/GameEngine/Source/Common/StatsCollector.cpp
    GeneralsMD/Code/GameEngine/Source/Common/System/BuildAssistant.cpp
    GeneralsMD/Code/GameEngine/Source/Common/System/CriticalSection.cpp
    GeneralsMD/Code/GameEngine/Source/Common/System/DataChunk.cpp
    GeneralsMD/Code/GameEngine/Source/Common/System/Directory.cpp
    GeneralsMD/Code/GameEngine/Source/Common/System/DisabledTypes.cpp
    GeneralsMD/Code/GameEngine/Source/Common/System/FunctionLexicon.cpp
    GeneralsMD/Code/GameEngine/Source/Common/System/Geometry.cpp
    GeneralsMD/Code/GameEngine/Source/Common/System/KindOf.cpp
    GeneralsMD/Code/GameEngine/Source/Common/System/List.cpp
    GeneralsMD/Code/GameEngine/Source/Common/System/QuotedPrintable.cpp
    GeneralsMD/Code/GameEngine/Source/Common/System/SaveGame/GameState.cpp
    GeneralsMD/Code/GameEngine/Source/Common/System/SaveGame/GameStateMap.cpp
    GeneralsMD/Code/GameEngine/Source/Common/System/StackDump.cpp
    GeneralsMD/Code/GameEngine/Source/Common/System/Trig.cpp
    GeneralsMD/Code/GameEngine/Source/Common/System/Upgrade.cpp
    GeneralsMD/Code/GameEngine/Source/Common/System/encrypt.cpp
    GeneralsMD/Code/GameEngine/Source/Common/System/registry.cpp
    GeneralsMD/Code/GameEngine/Source/Common/TerrainTypes.cpp
    GeneralsMD/Code/GameEngine/Source/Common/Thing/DrawModule.cpp
    GeneralsMD/Code/GameEngine/Source/Common/Thing/Module.cpp
    GeneralsMD/Code/GameEngine/Source/Common/Thing/ModuleFactory.cpp
    GeneralsMD/Code/GameEngine/Source/Common/Thing/Thing.cpp
    GeneralsMD/Code/GameEngine/Source/Common/Thing/ThingFactory.cpp
    GeneralsMD/Code/GameEngine/Source/Common/Thing/ThingTemplate.cpp
    GeneralsMD/Code/GameEngine/Source/Common/version.cpp
    GeneralsMD/Code/GameEngine/Source/GameClient/Display.cpp
    GeneralsMD/Code/GameEngine/Source/GameClient/Drawable.cpp
    GeneralsMD/Code/GameEngine/Source/GameClient/Drawable/Update/AnimatedParticleSysBoneClientUpdate.cpp
    GeneralsMD/Code/GameEngine/Source/GameClient/Drawable/Update/BeaconClientUpdate.cpp
    GeneralsMD/Code/GameEngine/Source/GameClient/Drawable/Update/SwayClientUpdate.cpp
    GeneralsMD/Code/GameEngine/Source/GameClient/Eva.cpp
    GeneralsMD/Code/GameEngine/Source/GameClient/GUI/AnimateWindowManager.cpp
    GeneralsMD/Code/GameEngine/Source/GameClient/GUI/ControlBar/ControlBar.cpp
    GeneralsMD/Code/GameEngine/Source/GameClient/GUI/ControlBar/ControlBarBeacon.cpp
    GeneralsMD/Code/GameEngine/Source/GameClient/GUI/ControlBar/ControlBarCommand.cpp
    GeneralsMD/Code/GameEngine/Source/GameClient/GUI/ControlBar/ControlBarCommandProcessing.cpp
    GeneralsMD/Code/GameEngine/Source/GameClient/GUI/ControlBar/ControlBarMultiSelect.cpp
    GeneralsMD/Code/GameEngine/Source/GameClient/GUI/ControlBar/ControlBarOCLTimer.cpp
    GeneralsMD/Code/GameEngine/Source/GameClient/GUI/ControlBar/ControlBarObserver.cpp
    GeneralsMD/Code/GameEngine/Source/GameClient/GUI/ControlBar/ControlBarPrintPositions.cpp
    GeneralsMD/Code/GameEngine/Source/GameClient/GUI/ControlBar/ControlBarResizer.cpp
    GeneralsMD/Code/GameEngine/Source/GameClient/GUI/ControlBar/ControlBarScheme.cpp
    GeneralsMD/Code/GameEngine/Source/GameClient/GUI/ControlBar/ControlBarStructureInventory.cpp
    GeneralsMD/Code/GameEngine/Source/GameClient/GUI/ControlBar/ControlBarUnderConstruction.cpp
    GeneralsMD/Code/GameEngine/Source/GameClient/GUI/DisconnectMenu/DisconnectMenu.cpp
    GeneralsMD/Code/GameEngine/Source/GameClient/GUI/EstablishConnectionsMenu/EstablishConnectionsMenu.cpp
    GeneralsMD/Code/GameEngine/Source/GameClient/GUI/GUICallbacks/ControlBarCallback.cpp
    GeneralsMD/Code/GameEngine/Source/GameClient/GUI/GUICallbacks/ControlBarPopupDescription.cpp
    GeneralsMD/Code/GameEngine/Source/GameClient/GUI/GUICallbacks/Diplomacy.cpp
    GeneralsMD/Code/GameEngine/Source/GameClient/GUI/GUICallbacks/ExtendedMessageBox.cpp
    GeneralsMD/Code/GameEngine/Source/GameClient/GUI/GUICallbacks/GeneralsExpPoints.cpp
    GeneralsMD/Code/GameEngine/Source/GameClient/GUI/GUICallbacks/IMECandidate.cpp
    GeneralsMD/Code/GameEngine/Source/GameClient/GUI/GUICallbacks/InGameChat.cpp
    GeneralsMD/Code/GameEngine/Source/GameClient/GUI/GUICallbacks/InGamePopupMessage.cpp
    GeneralsMD/Code/GameEngine/Source/GameClient/GUI/GUICallbacks/Menus/ChallengeMenu.cpp
    GeneralsMD/Code/GameEngine/Source/GameClient/GUI/GUICallbacks/Menus/CreditsMenu.cpp
    GeneralsMD/Code/GameEngine/Source/GameClient/GUI/GUICallbacks/Menus/DifficultySelect.cpp
    GeneralsMD/Code/GameEngine/Source/GameClient/GUI/GUICallbacks/Menus/DisconnectWindow.cpp
    GeneralsMD/Code/GameEngine/Source/GameClient/GUI/GUICallbacks/Menus/DownloadMenu.cpp
    GeneralsMD/Code/GameEngine/Source/GameClient/GUI/GUICallbacks/Menus/EstablishConnectionsWindow.cpp
    GeneralsMD/Code/GameEngine/Source/GameClient/GUI/GUICallbacks/Menus/GameInfoWindow.cpp
    GeneralsMD/Code/GameEngine/Source/GameClient/GUI/GUICallbacks/Menus/KeyboardOptionsMenu.cpp
    GeneralsMD/Code/GameEngine/Source/GameClient/GUI/GUICallbacks/Menus/LanGameOptionsMenu.cpp
    GeneralsMD/Code/GameEngine/Source/GameClient/GUI/GUICallbacks/Menus/LanLobbyMenu.cpp
    GeneralsMD/Code/GameEngine/Source/GameClient/GUI/GUICallbacks/Menus/LanMapSelectMenu.cpp
    GeneralsMD/Code/GameEngine/Source/GameClient/GUI/GUICallbacks/Menus/MainMenu.cpp
    GeneralsMD/Code/GameEngine/Source/GameClient/GUI/GUICallbacks/Menus/MapSelectMenu.cpp
    GeneralsMD/Code/GameEngine/Source/GameClient/GUI/GUICallbacks/Menus/NetworkDirectConnect.cpp
    GeneralsMD/Code/GameEngine/Source/GameClient/GUI/GUICallbacks/Menus/OptionsMenu.cpp
    GeneralsMD/Code/GameEngine/Source/GameClient/GUI/GUICallbacks/Menus/PopupCommunicator.cpp
    GeneralsMD/Code/GameEngine/Source/GameClient/GUI/GUICallbacks/Menus/PopupReplay.cpp
    GeneralsMD/Code/GameEngine/Source/GameClient/GUI/GUICallbacks/Menus/PopupSaveLoad.cpp
    GeneralsMD/Code/GameEngine/Source/GameClient/GUI/GUICallbacks/Menus/QuitMenu.cpp
    GeneralsMD/Code/GameEngine/Source/GameClient/GUI/GUICallbacks/Menus/ReplayMenu.cpp
    GeneralsMD/Code/GameEngine/Source/GameClient/GUI/GUICallbacks/Menus/ScoreScreen.cpp
    GeneralsMD/Code/GameEngine/Source/GameClient/GUI/GUICallbacks/Menus/SinglePlayerMenu.cpp
    GeneralsMD/Code/GameEngine/Source/GameClient/GUI/GUICallbacks/Menus/SkirmishGameOptionsMenu.cpp
    GeneralsMD/Code/GameEngine/Source/GameClient/GUI/GUICallbacks/Menus/SkirmishMapSelectMenu.cpp
    GeneralsMD/Code/GameEngine/Source/GameClient/GUI/GUICallbacks/MessageBox.cpp
    GeneralsMD/Code/GameEngine/Source/GameClient/GUI/GUICallbacks/ReplayControls.cpp
    GeneralsMD/Code/GameEngine/Source/GameClient/GUI/Gadget/GadgetCheckBox.cpp
    GeneralsMD/Code/GameEngine/Source/GameClient/GUI/Gadget/GadgetComboBox.cpp
    GeneralsMD/Code/GameEngine/Source/GameClient/GUI/Gadget/GadgetHorizontalSlider.cpp
    GeneralsMD/Code/GameEngine/Source/GameClient/GUI/Gadget/GadgetListBox.cpp
    GeneralsMD/Code/GameEngine/Source/GameClient/GUI/Gadget/GadgetProgressBar.cpp
    GeneralsMD/Code/GameEngine/Source/GameClient/GUI/Gadget/GadgetPushButton.cpp
    GeneralsMD/Code/GameEngine/Source/GameClient/GUI/Gadget/GadgetRadioButton.cpp
    GeneralsMD/Code/GameEngine/Source/GameClient/GUI/Gadget/GadgetStaticText.cpp
    GeneralsMD/Code/GameEngine/Source/GameClient/GUI/Gadget/GadgetTabControl.cpp
    GeneralsMD/Code/GameEngine/Source/GameClient/GUI/Gadget/GadgetTextEntry.cpp
    GeneralsMD/Code/GameEngine/Source/GameClient/GUI/Gadget/GadgetVerticalSlider.cpp
    GeneralsMD/Code/GameEngine/Source/GameClient/GUI/GameWindowManager.cpp
    GeneralsMD/Code/GameEngine/Source/GameClient/GUI/GameWindowManagerScript.cpp
    GeneralsMD/Code/GameEngine/Source/GameClient/GUI/GameWindowTransitionsStyles.cpp
    GeneralsMD/Code/GameEngine/Source/GameClient/GUI/Shell/Shell.cpp
    GeneralsMD/Code/GameEngine/Source/GameClient/GUI/Shell/ShellMenuScheme.cpp
    GeneralsMD/Code/GameEngine/Source/GameClient/GameClient.cpp
    GeneralsMD/Code/GameEngine/Source/GameClient/GameClientDispatch.cpp
    GeneralsMD/Code/GameEngine/Source/GameClient/InGameUI.cpp
    GeneralsMD/Code/GameEngine/Source/GameClient/MessageStream/CommandXlat.cpp
    GeneralsMD/Code/GameEngine/Source/GameClient/MessageStream/GUICommandTranslator.cpp
    GeneralsMD/Code/GameEngine/Source/GameClient/MessageStream/HintSpy.cpp
    GeneralsMD/Code/GameEngine/Source/GameClient/MessageStream/HotKey.cpp
    GeneralsMD/Code/GameEngine/Source/GameClient/MessageStream/LookAtXlat.cpp
    GeneralsMD/Code/GameEngine/Source/GameClient/MessageStream/MetaEvent.cpp
    GeneralsMD/Code/GameEngine/Source/GameClient/MessageStream/PlaceEventTranslator.cpp
    GeneralsMD/Code/GameEngine/Source/GameClient/MessageStream/SelectionXlat.cpp
    GeneralsMD/Code/GameEngine/Source/GameClient/MessageStream/WindowXlat.cpp
    GeneralsMD/Code/GameEngine/Source/GameClient/System/Anim2D.cpp
    GeneralsMD/Code/GameEngine/Source/GameClient/System/CampaignManager.cpp
    GeneralsMD/Code/GameEngine/Source/GameClient/System/DebugDisplay.cpp
    GeneralsMD/Code/GameEngine/Source/GameClient/System/Image.cpp
    GeneralsMD/Code/GameEngine/Source/GameClient/System/RayEffect.cpp
    GeneralsMD/Code/GameEngine/Source/GameLogic/AI/AI.cpp
    GeneralsMD/Code/GameEngine/Source/GameLogic/AI/AIDock.cpp
    GeneralsMD/Code/GameEngine/Source/GameLogic/AI/AIGroup.cpp
    GeneralsMD/Code/GameEngine/Source/GameLogic/AI/AIGuard.cpp
    GeneralsMD/Code/GameEngine/Source/GameLogic/AI/AIGuardRetaliate.cpp
    GeneralsMD/Code/GameEngine/Source/GameLogic/AI/AIPathfind.cpp
    GeneralsMD/Code/GameEngine/Source/GameLogic/AI/AIPlayer.cpp
    GeneralsMD/Code/GameEngine/Source/GameLogic/AI/AISkirmishPlayer.cpp
    GeneralsMD/Code/GameEngine/Source/GameLogic/AI/AIStates.cpp
    GeneralsMD/Code/GameEngine/Source/GameLogic/AI/AITNGuard.cpp
    GeneralsMD/Code/GameEngine/Source/GameLogic/AI/Squad.cpp
    GeneralsMD/Code/GameEngine/Source/GameLogic/AI/TurretAI.cpp
    GeneralsMD/Code/GameEngine/Source/GameLogic/Map/PolygonTrigger.cpp
    GeneralsMD/Code/GameEngine/Source/GameLogic/Map/SidesList.cpp
    GeneralsMD/Code/GameEngine/Source/GameLogic/Map/TerrainLogic.cpp
    GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Armor.cpp
    GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Behavior/AutoHealBehavior.cpp
    GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Behavior/BattleBusSlowDeathBehavior.cpp
    GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Behavior/BehaviorModule.cpp
    GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Behavior/BridgeBehavior.cpp
    GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Behavior/BridgeScaffoldBehavior.cpp
    GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Behavior/BridgeTowerBehavior.cpp
    GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Behavior/BunkerBusterBehavior.cpp
    GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Behavior/CountermeasuresBehavior.cpp
    GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Behavior/DumbProjectileBehavior.cpp
    GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Behavior/FireWeaponWhenDamagedBehavior.cpp
    GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Behavior/FireWeaponWhenDeadBehavior.cpp
    GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Behavior/FlightDeckBehavior.cpp
    GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Behavior/GenerateMinefieldBehavior.cpp
    GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Behavior/GrantStealthBehavior.cpp
    GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Behavior/InstantDeathBehavior.cpp
    GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Behavior/JetSlowDeathBehavior.cpp
    GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Behavior/MinefieldBehavior.cpp
    GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Behavior/NeutonBlastBehavior.cpp
    GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Behavior/OverchargeBehavior.cpp
    GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Behavior/POWTruckBehavior.cpp
    GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Behavior/ParkingPlaceBehavior.cpp
    GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Behavior/PoisonedBehavior.cpp
    GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Behavior/PrisonBehavior.cpp
    GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Behavior/PropagandaCenterBehavior.cpp
    GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Behavior/PropagandaTowerBehavior.cpp
    GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Behavior/RebuildHoleBehavior.cpp
    GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Behavior/SlowDeathBehavior.cpp
    GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Behavior/SpawnBehavior.cpp
    GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Behavior/SupplyWarehouseCripplingBehavior.cpp
    GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Behavior/TechBuildingBehavior.cpp
    GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Body/ActiveBody.cpp
    GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Body/BodyModule.cpp
    GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Body/HighlanderBody.cpp
    GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Body/HiveStructureBody.cpp
    GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Body/ImmortalBody.cpp
    GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Body/InactiveBody.cpp
    GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Body/StructureBody.cpp
    GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Body/UndeadBody.cpp
    GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Collide/CollideModule.cpp
    GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Collide/CrateCollide/ConvertToCarBombCrateCollide.cpp
    GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Collide/CrateCollide/ConvertToHijackedVehicleCrateCollide.cpp
    GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Collide/CrateCollide/CrateCollide.cpp
    GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Collide/CrateCollide/HealCrateCollide.cpp
    GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Collide/CrateCollide/MoneyCrateCollide.cpp
    GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Collide/CrateCollide/SabotageCommandCenterCrateCollide.cpp
    GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Collide/CrateCollide/SabotageFakeBuilding.cpp
    GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Collide/CrateCollide/SabotageInternetCenterCrateCollide.cpp
    GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Collide/CrateCollide/SabotageMilitaryFactoryCrateCollide.cpp
    GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Collide/CrateCollide/SabotagePowerPlantCrateCollide.cpp
    GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Collide/CrateCollide/SabotageSuperweaponCrateCollide.cpp
    GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Collide/CrateCollide/SabotageSupplyCenterCrateCollide.cpp
    GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Collide/CrateCollide/SabotageSupplyDropzoneCrateCollide.cpp
    GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Collide/CrateCollide/SalvageCrateCollide.cpp
    GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Collide/CrateCollide/ShroudCrateCollide.cpp
    GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Collide/CrateCollide/UnitCrateCollide.cpp
    GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Collide/CrateCollide/VeterancyCrateCollide.cpp
    GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Collide/FireWeaponCollide.cpp
    GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Collide/SquishCollide.cpp
    GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Contain/CaveContain.cpp
    GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Contain/GarrisonContain.cpp
    GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Contain/HealContain.cpp
    GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Contain/HelixContain.cpp
    GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Contain/InternetHackContain.cpp
    GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Contain/MobNexusContain.cpp
    GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Contain/OpenContain.cpp
    GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Contain/OverlordContain.cpp
    GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Contain/ParachuteContain.cpp
    GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Contain/RailedTransportContain.cpp
    GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Contain/RiderChangeContain.cpp
    GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Contain/TransportContain.cpp
    GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Contain/TunnelContain.cpp
    GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Create/CreateModule.cpp
    GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Create/GrantUpgradeCreate.cpp
    GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Create/LockWeaponCreate.cpp
    GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Create/PreorderCreate.cpp
    GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Create/SpecialPowerCreate.cpp
    GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Create/SupplyCenterCreate.cpp
    GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Create/SupplyWarehouseCreate.cpp
    GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Create/VeterancyGainCreate.cpp
    GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Damage/BoneFXDamage.cpp
    GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Damage/DamageModule.cpp
    GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Damage/TransitionDamageFX.cpp
    GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Destroy/DestroyModule.cpp
    GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Die/CreateCrateDie.cpp
    GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Die/CreateObjectDie.cpp
    GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Die/CrushDie.cpp
    GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Die/DamDie.cpp
    GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Die/DestroyDie.cpp
    GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Die/DieModule.cpp
    GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Die/EjectPilotDie.cpp
    GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Die/FXListDie.cpp
    GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Die/KeepObjectDie.cpp
    GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Die/RebuildHoleExposeDie.cpp
    GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Die/SpecialPowerCompletionDie.cpp
    GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Die/UpgradeDie.cpp
    GeneralsMD/Code/GameEngine/Source/GameLogic/Object/ExperienceTracker.cpp
    GeneralsMD/Code/GameEngine/Source/GameLogic/Object/FiringTracker.cpp
    GeneralsMD/Code/GameEngine/Source/GameLogic/Object/GhostObject.cpp
    GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Helper/ObjectDefectionHelper.cpp
    GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Helper/ObjectHelper.cpp
    GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Helper/ObjectRepulsorHelper.cpp
    GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Helper/ObjectSMCHelper.cpp
    GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Helper/ObjectWeaponStatusHelper.cpp
    GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Helper/StatusDamageHelper.cpp
    GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Helper/SubdualDamageHelper.cpp
    GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Helper/TempWeaponBonusHelper.cpp
    GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Locomotor.cpp
    GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Object.cpp
    GeneralsMD/Code/GameEngine/Source/GameLogic/Object/ObjectCreationList.cpp
    GeneralsMD/Code/GameEngine/Source/GameLogic/Object/ObjectTypes.cpp
    GeneralsMD/Code/GameEngine/Source/GameLogic/Object/PartitionManager.cpp
    GeneralsMD/Code/GameEngine/Source/GameLogic/Object/SimpleObjectIterator.cpp
    GeneralsMD/Code/GameEngine/Source/GameLogic/Object/SpecialPower/BaikonurLaunchPower.cpp
    GeneralsMD/Code/GameEngine/Source/GameLogic/Object/SpecialPower/CashBountyPower.cpp
    GeneralsMD/Code/GameEngine/Source/GameLogic/Object/SpecialPower/CashHackSpecialPower.cpp
    GeneralsMD/Code/GameEngine/Source/GameLogic/Object/SpecialPower/CleanupAreaPower.cpp
    GeneralsMD/Code/GameEngine/Source/GameLogic/Object/SpecialPower/DefectorSpecialPower.cpp
    GeneralsMD/Code/GameEngine/Source/GameLogic/Object/SpecialPower/DemoralizeSpecialPower.cpp
    GeneralsMD/Code/GameEngine/Source/GameLogic/Object/SpecialPower/FireWeaponPower.cpp
    GeneralsMD/Code/GameEngine/Source/GameLogic/Object/SpecialPower/OCLSpecialPower.cpp
    GeneralsMD/Code/GameEngine/Source/GameLogic/Object/SpecialPower/SpecialAbility.cpp
    GeneralsMD/Code/GameEngine/Source/GameLogic/Object/SpecialPower/SpecialPowerModule.cpp
    GeneralsMD/Code/GameEngine/Source/GameLogic/Object/SpecialPower/SpyVisionSpecialPower.cpp
    GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Update/AIUpdate.cpp
    GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Update/AIUpdate/AssaultTransportAIUpdate.cpp
    GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Update/AIUpdate/ChinookAIUpdate.cpp
    GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Update/AIUpdate/DeliverPayloadAIUpdate.cpp
    GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Update/AIUpdate/DeployStyleAIUpdate.cpp
    GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Update/AIUpdate/DozerAIUpdate.cpp
    GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Update/AIUpdate/HackInternetAIUpdate.cpp
    GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Update/AIUpdate/JetAIUpdate.cpp
    GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Update/AIUpdate/MissileAIUpdate.cpp
    GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Update/AIUpdate/POWTruckAIUpdate.cpp
    GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Update/AIUpdate/RailedTransportAIUpdate.cpp
    GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Update/AIUpdate/RailroadGuideAIUpdate.cpp
    GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Update/AIUpdate/SupplyTruckAIUpdate.cpp
    GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Update/AIUpdate/TransportAIUpdate.cpp
    GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Update/AIUpdate/WanderAIUpdate.cpp
    GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Update/AIUpdate/WorkerAIUpdate.cpp
    GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Update/AnimationSteeringUpdate.cpp
    GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Update/AssistedTargetingUpdate.cpp
    GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Update/AutoDepositUpdate.cpp
    GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Update/AutoFindHealingUpdate.cpp
    GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Update/BaseRenerateUpdate.cpp
    GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Update/BattlePlanUpdate.cpp
    GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Update/BoneFXUpdate.cpp
    GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Update/CheckpointUpdate.cpp
    GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Update/CleanupHazardUpdate.cpp
    GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Update/CommandButtonHuntUpdate.cpp
    GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Update/DeletionUpdate.cpp
    GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Update/DemoTrapUpdate.cpp
    GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Update/DockUpdate/DockUpdate.cpp
    GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Update/DockUpdate/PrisonDockUpdate.cpp
    GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Update/DockUpdate/RailedTransportDockUpdate.cpp
    GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Update/DockUpdate/RepairDockUpdate.cpp
    GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Update/DockUpdate/SupplyCenterDockUpdate.cpp
    GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Update/DockUpdate/SupplyWarehouseDockUpdate.cpp
    GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Update/DynamicGeometryInfoUpdate.cpp
    GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Update/DynamicShroudClearingRangeUpdate.cpp
    GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Update/EMPUpdate.cpp
    GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Update/EnemyNearUpdate.cpp
    GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Update/FireOCLAfterWeaponCooldownUpdate.cpp
    GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Update/FireSpreadUpdate.cpp
    GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Update/FireWeaponUpdate.cpp
    GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Update/FirestormDynamicGeometryInfoUpdate.cpp
    GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Update/FlammableUpdate.cpp
    GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Update/FloatUpdate.cpp
    GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Update/HeightDieUpdate.cpp
    GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Update/HelicopterSlowDeathUpdate.cpp
    GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Update/HijackerUpdate.cpp
    GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Update/HordeUpdate.cpp
    GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Update/LaserUpdate.cpp
    GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Update/LifetimeUpdate.cpp
    GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Update/MissileLauncherBuildingUpdate.cpp
    GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Update/MobMemberSlavedUpdate.cpp
    GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Update/NeutronMissileSlowDeathUpdate.cpp
    GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Update/NeutronMissileUpdate.cpp
    GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Update/OCLUpdate.cpp
    GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Update/ParticleUplinkCannonUpdate.cpp
    GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Update/PhysicsUpdate.cpp
    GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Update/PilotFindVehicleUpdate.cpp
    GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Update/PointDefenseLaserUpdate.cpp
    GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Update/PowerPlantUpdate.cpp
    GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Update/ProductionExitUpdate/DefaultProductionExitUpdate.cpp
    GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Update/ProductionExitUpdate/QueueProductionExitUpdate.cpp
    GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Update/ProductionExitUpdate/SpawnPointProductionExitUpdate.cpp
    GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Update/ProductionExitUpdate/SupplyCenterProductionExitUpdate.cpp
    GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Update/ProductionUpdate.cpp
    GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Update/ProjectileStreamUpdate.cpp
    GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Update/ProneUpdate.cpp
    GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Update/RadarUpdate.cpp
    GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Update/RadiusDecalUpdate.cpp
    GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Update/SlavedUpdate.cpp
    GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Update/SmartBombTargetHomingUpdate.cpp
    GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Update/SpecialAbilityUpdate.cpp
    GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Update/SpecialPowerUpdateModule.cpp
    GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Update/SpectreGunshipDeploymentUpdate.cpp
    GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Update/SpectreGunshipUpdate.cpp
    GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Update/SpyVisionUpdate.cpp
    GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Update/StealthDetectorUpdate.cpp
    GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Update/StealthUpdate.cpp
    GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Update/StickyBombUpdate.cpp
    GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Update/StructureCollapseUpdate.cpp
    GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Update/StructureToppleUpdate.cpp
    GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Update/TensileFormationUpdate.cpp
    GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Update/ToppleUpdate.cpp
    GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Update/UpdateModule.cpp
    GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Update/WaveGuideUpdate.cpp
    GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Update/WeaponBonusUpdate.cpp
    GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Upgrade/ActiveShroudUpgrade.cpp
    GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Upgrade/ArmorUpgrade.cpp
    GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Upgrade/CommandSetUpgrade.cpp
    GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Upgrade/CostModifierUpgrade.cpp
    GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Upgrade/ExperienceScalarUpgrade.cpp
    GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Upgrade/GrantScienceUpgrade.cpp
    GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Upgrade/LocomotorSetUpgrade.cpp
    GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Upgrade/MaxHealthUpgrade.cpp
    GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Upgrade/ModelConditionUpgrade.cpp
    GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Upgrade/ObjectCreationUpgrade.cpp
    GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Upgrade/PassengersFireUpgrade.cpp
    GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Upgrade/PowerPlantUpgrade.cpp
    GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Upgrade/RadarUpgrade.cpp
    GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Upgrade/ReplaceObjectUpgrade.cpp
    GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Upgrade/StatusBitsUpgrade.cpp
    GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Upgrade/StealthUpgrade.cpp
    GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Upgrade/SubObjectsUpgrade.cpp
    GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Upgrade/UnpauseSpecialPowerUpgrade.cpp
    GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Upgrade/UpgradeModule.cpp
    GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Upgrade/WeaponBonusUpgrade.cpp
    GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Upgrade/WeaponSetUpgrade.cpp
    GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Weapon.cpp
    GeneralsMD/Code/GameEngine/Source/GameLogic/Object/WeaponSet.cpp
    GeneralsMD/Code/GameEngine/Source/GameLogic/ScriptEngine/ScriptActions.cpp
    GeneralsMD/Code/GameEngine/Source/GameLogic/ScriptEngine/ScriptConditions.cpp
    GeneralsMD/Code/GameEngine/Source/GameLogic/ScriptEngine/ScriptEngine.cpp
    GeneralsMD/Code/GameEngine/Source/GameLogic/ScriptEngine/Scripts.cpp
    GeneralsMD/Code/GameEngine/Source/GameLogic/ScriptEngine/VictoryConditions.cpp
    GeneralsMD/Code/GameEngine/Source/GameLogic/System/CaveSystem.cpp
    GeneralsMD/Code/GameEngine/Source/GameLogic/System/CrateSystem.cpp
    GeneralsMD/Code/GameEngine/Source/GameLogic/System/Damage.cpp
    GeneralsMD/Code/GameEngine/Source/GameLogic/System/GameLogic.cpp
    GeneralsMD/Code/GameEngine/Source/GameLogic/System/GameLogicDispatch.cpp
    GeneralsMD/Code/GameEngine/Source/GameLogic/System/GameTelemetry.cpp
    GeneralsMD/Code/GameEngine/Source/GameLogic/System/RankInfo.cpp
    GeneralsMD/Code/GameEngine/Source/GameNetwork/GUIUtil.cpp
    GeneralsMD/Code/GameEngine/Source/Precompiled/PreRTS.cpp
    GeneralsMD/Code/Libraries/Source/WWVegas/WW3D2/TerrainTexStubs.cpp
    GeneralsMD/Code/Libraries/Source/WWVegas/WW3D2/aabtreebuilder.cpp
    GeneralsMD/Code/Libraries/Source/WWVegas/WW3D2/animobj.cpp
    GeneralsMD/Code/Libraries/Source/WWVegas/WW3D2/camera.cpp
    GeneralsMD/Code/Libraries/Source/WWVegas/WW3D2/hanimmgr.cpp
    GeneralsMD/Code/Libraries/Source/WWVegas/WW3D2/hlod.cpp
    GeneralsMD/Code/Libraries/Source/WWVegas/WW3D2/hmorphanim.cpp
    GeneralsMD/Code/Libraries/Source/WWVegas/WW3D2/hrawanim.cpp
    GeneralsMD/Code/Libraries/Source/WWVegas/WW3D2/htreemgr.cpp
    GeneralsMD/Code/Libraries/Source/WWVegas/WW3D2/light.cpp
    GeneralsMD/Code/Libraries/Source/WWVegas/WW3D2/lightenvironment.cpp
    GeneralsMD/Code/Libraries/Source/WWVegas/WW3D2/meshgeometry.cpp
    GeneralsMD/Code/Libraries/Source/WWVegas/WW3D2/meshmatdesc.cpp
    GeneralsMD/Code/Libraries/Source/WWVegas/WW3D2/meshmdlio.cpp
    GeneralsMD/Code/Libraries/Source/WWVegas/WW3D2/motchan.cpp
    GeneralsMD/Code/Libraries/Source/WWVegas/WW3D2/nullrobj.cpp
    GeneralsMD/Code/Libraries/Source/WWVegas/WW3D2/rinfo.cpp
    GeneralsMD/Code/Libraries/Source/WWVegas/WW3D2/scene.cpp
    GeneralsMD/Code/Libraries/Source/WWVegas/WW3D2/shader.cpp
    GeneralsMD/Code/Libraries/Source/WWVegas/WW3D2/vertmaterial.cpp
    GeneralsMD/Code/Main/VideoEnhancer.cpp
    GeneralsMD/Code/Main/WinMain.cpp
    Renderer/Core/Buffer.cpp
    Renderer/Core/Device.cpp
    Renderer/Core/Shader.cpp
    Renderer/Core/Texture.cpp
    Renderer/Renderer.cpp
    Renderer/DebugDraw.cpp
    Renderer/GPUParticles.cpp
    Renderer/Core/Vulkan/DeviceVK.cpp
    Renderer/Core/Vulkan/BufferVK.cpp
    Renderer/Core/Vulkan/VulkanUtil.cpp
    Renderer/Core/Vulkan/TextureVK.cpp
    Renderer/Core/Vulkan/ShaderVK.cpp
    Renderer/Core/Vulkan/VulkanPipeline.cpp
    Renderer/Core/Vulkan/VmaImpl.cpp
    Renderer/Core/ShaderCompiler.cpp
    Platform/SDLPlatform.cpp
    Platform/SDLMouse.cpp
    Platform/SDLKeyboard.cpp
    Platform/SDLGameEngine.cpp
    Platform/SDLAudioManager.cpp
    Platform/AniCursor.cpp
    Inspector/Inspector.cpp
    Inspector/Panels.cpp
    Inspector/AIPanels.cpp
    Inspector/HudPanels.cpp
    Inspector/ScriptPanel.cpp
    Inspector/DestructionTimeline.cpp
    extern/imgui/imgui.cpp
    extern/imgui/imgui_draw.cpp
    extern/imgui/imgui_tables.cpp
    extern/imgui/imgui_widgets.cpp
    extern/imgui/imgui_demo.cpp
    extern/imgui/backends/imgui_impl_sdl3.cpp
    extern/imgui/backends/imgui_impl_dx11.cpp
    extern/lzhl_wrapper/CompLibHeader/Huff.cpp
    extern/lzhl_wrapper/CompLibHeader/Lz.cpp
    extern/lzhl_wrapper/CompLibHeader/Lzhl.cpp
    extern/zlib/adler32.c
    extern/zlib/compress.c
    extern/zlib/crc32.c
    extern/zlib/deflate.c
    extern/zlib/gzio.c
    extern/zlib/infblock.c
    extern/zlib/infcodes.c
    extern/zlib/inffast.c
    extern/zlib/inflate.c
    extern/zlib/inftrees.c
    extern/zlib/infutil.c
    extern/zlib/trees.c
    extern/zlib/uncompr.c
    extern/zlib/zutil.c
)
